eureka:
  instance:
    appname: oauth2-server
    instance-id: oauth2-server
  client:
    service-url: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
spring:
  application:
    name: actuator
server:
  port: 8888





